export type PdCategory = {
  id: string
  emoji: string
  title: string
  blurb: string
  courses: readonly string[]
}

export const PD_CATALOG: readonly PdCategory[] = [
  // ── Future industries ──────────────────────────────────────────────
  {
    id: "future-ai",
    emoji: "🤖",
    title: "Artificial Intelligence",
    blurb: "Models, agents, and systems that redefine work and industry.",
    courses: [
      "AI Foundations",
      "Machine Learning Systems",
      "Deep Learning",
      "Generative AI",
      "Large Language Models",
      "AI Agents & Tool Use",
      "Multimodal AI",
      "AI Safety & Alignment Basics",
      "MLOps for Production",
      "AI Product Strategy",
      "Computer Vision Futures",
      "Responsible AI Practice",
    ],
  },
  {
    id: "future-quantum",
    emoji: "⚛",
    title: "Quantum Computing",
    blurb: "Qubits, algorithms, and the next computing paradigm.",
    courses: [
      "Quantum Computing Fundamentals",
      "Qubits & Quantum Gates",
      "Quantum Algorithms",
      "Quantum Error Correction Intro",
      "Quantum Machine Learning",
      "Quantum Cryptography",
      "Quantum Hardware Landscape",
      "Quantum Software Stacks",
      "Near-Term Quantum Applications",
      "Quantum Industry Roadmap",
    ],
  },
  {
    id: "future-space-economy",
    emoji: "🚀",
    title: "Space Economy",
    blurb: "Commercial space, orbital industry, and off-world markets.",
    courses: [
      "Introduction to the Space Economy",
      "Commercial Launch Markets",
      "Satellite Business Models",
      "NewSpace Entrepreneurship",
      "Space Investment & Finance",
      "Lunar Economy Concepts",
      "Orbital Manufacturing Markets",
      "Space Policy for Builders",
      "Earth Observation Commerce",
      "Interplanetary Industry Futures",
    ],
  },
  {
    id: "future-biotech",
    emoji: "🧬",
    title: "Biotechnology",
    blurb: "Life sciences that reshape medicine, food, and materials.",
    courses: [
      "Biotechnology Fundamentals",
      "Genetic Engineering Basics",
      "CRISPR & Gene Editing",
      "Synthetic Biology",
      "Biomanufacturing",
      "Bioinformatics Essentials",
      "Drug Discovery Pipelines",
      "Personalized Medicine Futures",
      "Agri-Biotech Systems",
      "Bioethics for Innovators",
    ],
  },
  {
    id: "future-nano",
    emoji: "🔬",
    title: "Nanotechnology",
    blurb: "Atomic-scale engineering for devices, energy, and medicine.",
    courses: [
      "Nanotechnology Foundations",
      "Nanomaterials",
      "Nanoelectronics Concepts",
      "Nanomedicine Intro",
      "Nanofabrication Methods",
      "Sensors at the Nanoscale",
      "Energy Nanotech",
      "Nano Safety & Regulation",
      "Characterization Techniques",
      "Nanotech Industry Applications",
    ],
  },
  {
    id: "future-materials",
    emoji: "🧱",
    title: "Advanced Materials",
    blurb: "Next-generation materials for aerospace, energy, and electronics.",
    courses: [
      "Advanced Materials Science",
      "Composites & Lightweight Structures",
      "Smart Materials",
      "Metamaterials Basics",
      "Battery Materials",
      "Semiconductor Materials Futures",
      "Additive Materials Systems",
      "Sustainable Materials Design",
      "Materials Characterization",
      "Materials for Extreme Environments",
    ],
  },
  {
    id: "future-fusion",
    emoji: "☀",
    title: "Fusion Energy",
    blurb: "Fusion science, engineering pathways, and energy futures.",
    courses: [
      "Fusion Energy Fundamentals",
      "Plasma Physics Essentials",
      "Magnetic Confinement Concepts",
      "Inertial Confinement Concepts",
      "Fusion Materials Challenges",
      "Fusion Plant Engineering Basics",
      "Fusion Startup Landscape",
      "Grid Integration Futures",
      "Safety & Licensing Overview",
      "Path to Commercial Fusion",
    ],
  },
  {
    id: "future-autonomous",
    emoji: "🛰",
    title: "Autonomous Systems",
    blurb: "Self-driving machines, drones, and decision autonomy at scale.",
    courses: [
      "Autonomous Systems Foundations",
      "Perception for Autonomy",
      "Planning & Control",
      "Autonomous Vehicles",
      "Drone Autonomy",
      "Multi-Agent Systems",
      "Safety Cases for Autonomy",
      "Simulation for Autonomy",
      "Human–Autonomy Teaming",
      "Autonomy Industry Roadmap",
    ],
  },
  {
    id: "future-bci",
    emoji: "🧠",
    title: "Brain-Computer Interfaces",
    blurb: "Neural interfaces linking mind, machine, and medicine.",
    courses: [
      "BCI Foundations",
      "Neural Signal Basics",
      "Invasive vs Non-Invasive BCI",
      "BCI for Assistive Tech",
      "Neuroprosthetics Intro",
      "Machine Learning for Neural Data",
      "BCI Hardware Landscape",
      "Ethics of Neural Interfaces",
      "Clinical BCI Pathways",
      "Future of Human–Machine Symbiosis",
    ],
  },
  {
    id: "future-nextgen-compute",
    emoji: "💡",
    title: "Next-Generation Computing",
    blurb: "Photonic, neuromorphic, edge, and post-Moore architectures.",
    courses: [
      "Post-Moore Computing Landscape",
      "Photonic Computing Intro",
      "Neuromorphic Computing Intro",
      "Edge & TinyML Systems",
      "High-Performance Computing Futures",
      "In-Memory Computing Concepts",
      "DNA & Unconventional Computing",
      "Hardware–Software Co-Design",
      "Compute for AI Workloads",
      "Building Tomorrow’s Compute Stack",
    ],
  },

  // ── Personal development (retained) ────────────────────────────────
  {
    id: "mindset",
    emoji: "🧠",
    title: "Mindset & Psychology",
    blurb: "Rewire beliefs, resilience, and the inner operating system.",
    courses: [
      "Growth Mindset Mastery",
      "Cognitive Biases & Clear Thinking",
      "Mental Models for Life",
      "Resilience Under Pressure",
      "Self-Awareness Deep Dive",
      "Identity & Habit Identity",
      "Overcoming Limiting Beliefs",
      "Stoic Practices for Modern Life",
      "Focus & Attention Control",
      "Emotional Regulation Systems",
    ],
  },
  {
    id: "habits",
    emoji: "⚡",
    title: "Habits & Discipline",
    blurb: "Build systems that compound daily excellence.",
    courses: [
      "Atomic Habits in Practice",
      "Discipline Without Burnout",
      "Morning & Evening Protocols",
      "Habit Stacking Systems",
      "Breaking Bad Loops",
      "Consistency Engineering",
      "Delayed Gratification Training",
      "Environment Design",
      "Accountability Architecture",
      "90-Day Transformation Sprints",
    ],
  },
  {
    id: "productivity",
    emoji: "🎯",
    title: "Productivity & Performance",
    blurb: "Output, energy, and high-performance operating rhythms.",
    courses: [
      "Deep Work Systems",
      "Time Architecture",
      "Priority Matrices that Work",
      "Second Brain & Knowledge Systems",
      "Energy Management",
      "Flow State Training",
      "Meeting & Calendar Mastery",
      "Procrastination Protocols",
      "Weekly Review Rituals",
      "Peak Performance Weeks",
    ],
  },
  {
    id: "communication",
    emoji: "🗣️",
    title: "Communication & Influence",
    blurb: "Speak, write, and persuade with clarity and presence.",
    courses: [
      "High-Impact Communication",
      "Public Speaking Mastery",
      "Storytelling for Leaders",
      "Persuasion & Negotiation",
      "Difficult Conversations",
      "Active Listening Systems",
      "Writing with Precision",
      "Executive Presence",
      "Nonverbal Intelligence",
      "Pitch & Presentation Design",
    ],
  },
  {
    id: "leadership",
    emoji: "👑",
    title: "Leadership & Character",
    blurb: "Lead people, decisions, and culture with integrity.",
    courses: [
      "Foundations of Leadership",
      "Emotional Intelligence for Leaders",
      "Decision Making Under Uncertainty",
      "Team Dynamics & Trust",
      "Conflict Resolution",
      "Coaching Conversations",
      "Vision & Strategy Craft",
      "Ethical Leadership",
      "Crisis Leadership",
      "Personal Brand of a Leader",
    ],
  },
  {
    id: "eq",
    emoji: "💜",
    title: "Emotional Intelligence",
    blurb: "Read rooms, regulate self, and build relational power.",
    courses: [
      "EQ Foundations",
      "Empathy in Action",
      "Social Awareness Training",
      "Relationship Management",
      "Anger & Stress Alchemy",
      "Compassion Protocols",
      "Boundary Setting",
      "Attachment Patterns",
      "Conflict Emotional Fluency",
      "EQ for High Achievers",
    ],
  },
  {
    id: "career",
    emoji: "🚀",
    title: "Career Acceleration",
    blurb: "Navigate roles, skills, and opportunity with intention.",
    courses: [
      "Career Strategy OS",
      "Personal Positioning",
      "Interview Mastery",
      "Networking that Compounds",
      "Skill Stacking for the Future",
      "Portfolio Career Design",
      "Promotion Playbooks",
      "Remote Work Excellence",
      "Mentorship Systems",
      "Career Pivot Frameworks",
    ],
  },
  {
    id: "finance",
    emoji: "💎",
    title: "Money & Wealth Mindset",
    blurb: "Financial literacy, behavior, and long-game wealth systems.",
    courses: [
      "Personal Finance Foundations",
      "Money Psychology",
      "Budgeting Systems that Stick",
      "Investing Literacy",
      "Risk & Decision Frameworks",
      "Wealth Building Habits",
      "Income Expansion Mindset",
      "Debt Clarity Protocols",
      "Long-Term Compounding",
      "Financial Independence Path",
    ],
  },
  {
    id: "health",
    emoji: "🌿",
    title: "Health & Vitality",
    blurb: "Body, sleep, and recovery as performance infrastructure.",
    courses: [
      "Sleep Optimization",
      "Nutrition for Focus",
      "Movement & Strength Basics",
      "Stress Physiology",
      "Breathwork Systems",
      "Recovery Protocols",
      "Digital Wellness",
      "Longevity Habits",
      "Energy Circadian Design",
      "Mind-Body Integration",
    ],
  },
  {
    id: "creativity",
    emoji: "✨",
    title: "Creativity & Innovation",
    blurb: "Idea generation, creative courage, and inventive practice.",
    courses: [
      "Creative Confidence",
      "Idea Generation Systems",
      "Design Thinking for Life",
      "Innovation Habits",
      "Creative Blocks & Flow",
      "Visual Thinking",
      "Writing as a Creative Craft",
      "Curiosity Protocols",
      "Experimentation Mindset",
      "Building Original Work",
    ],
  },
  {
    id: "relationships",
    emoji: "🤝",
    title: "Relationships & Social Mastery",
    blurb: "Trust, connection, and high-quality human networks.",
    courses: [
      "Relationship Foundations",
      "Trust Building",
      "Social Intelligence",
      "Friendship Systems",
      "Family Dynamics",
      "Professional Relationships",
      "Community Building",
      "Charisma Without Manipulation",
      "Repairing Broken Trust",
      "High-Quality Connections",
    ],
  },
  {
    id: "learning",
    emoji: "📚",
    title: "Learning & Meta-Skills",
    blurb: "Learn faster, remember longer, and transfer skill across domains.",
    courses: [
      "How to Learn Anything",
      "Memory Systems",
      "Speed Learning Protocols",
      "Deliberate Practice",
      "Note-Taking for Mastery",
      "Teaching to Learn",
      "Research Habits",
      "Critical Reading",
      "Skill Transfer Frameworks",
      "Lifelong Learning OS",
    ],
  },
  {
    id: "purpose",
    emoji: "🧭",
    title: "Purpose & Life Design",
    blurb: "Clarify direction, values, and a life worth compounding.",
    courses: [
      "Values Clarification",
      "Life Vision Architecture",
      "Ikigai & Meaningful Work",
      "Goal Systems that Survive Reality",
      "Quarterly Life Design",
      "Legacy Thinking",
      "Meaning Under Uncertainty",
      "Personal Mission Statement",
      "Aligning Ambition & Peace",
      "Designing a Decade",
    ],
  },
  {
    id: "digital",
    emoji: "🛰️",
    title: "Digital Self & Future Skills",
    blurb: "Presence, privacy, and human advantage in an AI world.",
    courses: [
      "Personal Brand in the AI Era",
      "Digital Presence Design",
      "Attention Economy Defense",
      "AI Collaboration Skills",
      "Information Hygiene",
      "Online Reputation Systems",
      "Creator Operating System",
      "Future of Work Fluency",
      "Human Edge Skills",
      "Tech-Life Integration",
    ],
  },
  {
    id: "confidence",
    emoji: "🔥",
    title: "Confidence & Courage",
    blurb: "Show up fully — in rooms, risks, and self-expression.",
    courses: [
      "Confidence Engineering",
      "Courage Under Judgment",
      "Imposter Syndrome Protocols",
      "Assertiveness Training",
      "Body Language Confidence",
      "Risk Tolerance Building",
      "Speaking Up Systems",
      "Self-Trust Practice",
      "Failure Recovery",
      "Bold Action Sprints",
    ],
  },
] as const

export const PD_TOTAL_COURSES = PD_CATALOG.reduce((n, c) => n + c.courses.length, 0)

export const PD_PATHS = [
  {
    id: "ai-frontier",
    title: "AI Frontier Path",
    body: "AI, agents, next-gen compute, and human collaboration skills.",
  },
  {
    id: "deep-tech",
    title: "Deep Tech Path",
    body: "Quantum, fusion, materials, nanotech, and biotech literacy.",
  },
  {
    id: "space-future",
    title: "Space Future Path",
    body: "Space economy fluency plus systems thinking for NewSpace careers.",
  },
  {
    id: "human-os",
    title: "Human OS Path",
    body: "Personal development — mindset, habits, leadership, and confidence.",
  },
] as const
