export const TIMELINE = [
  {
    year: "1957",
    title: "Sputnik",
    summary: "Humanity enters orbit — the space age begins.",
    importance: "Proved Earth orbit was reachable and ignited the global space race.",
    economic: "Created the first demand for launch, tracking, and radio science industries.",
    tech: ["Ballistic rocketry", "Telemetry", "Orbital mechanics"],
  },
  {
    year: "1969",
    title: "Moon Landing",
    summary: "Apollo proves crewed deep-space operations.",
    importance: "Systems engineering at planetary scale — computing, materials, life support.",
    economic: "Spillover into semiconductors, GPS precursors, and advanced manufacturing.",
    tech: ["Saturn V", "Guidance computers", "Heat shields"],
  },
  {
    year: "1981",
    title: "Space Shuttle",
    summary: "Reusable winged access to LEO.",
    importance: "Normalized crew + cargo missions and satellite servicing concepts.",
    economic: "Expanded commercial payload markets and spaceflight operations careers.",
    tech: ["Reusable orbiter", "SRBs", "RMS robotics"],
  },
  {
    year: "1998",
    title: "ISS",
    summary: "Permanent human presence in orbit.",
    importance: "International labs for biology, materials, and long-duration life support.",
    economic: "Research contracts, logistics resupply, and microgravity manufacturing R&D.",
    tech: ["Modular stations", "EVA systems", "Closed-loop life support"],
  },
  {
    year: "2008",
    title: "Private Space Era",
    summary: "Commercial cargo and private launch providers scale.",
    importance: "Competition drives cost curves down.",
    economic: "Venture capital enters launch, satcom, and Earth observation.",
    tech: ["Commercial crew/cargo", "New launch vehicles"],
  },
  {
    year: "2015",
    title: "Reusable Rockets",
    summary: "First-stage recovery becomes routine.",
    importance: "Launch cadence and price redefine access to space.",
    economic: "Enables mega-constellations and lower barrier for startups.",
    tech: ["Propulsive landing", "Rapid reuse", "Autonomous flight"],
  },
  {
    year: "2025",
    title: "Commercial Space Economy",
    summary: "Satellites, launch, and services become mainstream markets.",
    importance: "Space becomes infrastructure for Earth economies.",
    economic: "Hundreds of billions in projected market activity across sectors.",
    tech: ["Mega-LEO constellations", "Smallsats", "In-orbit services"],
  },
  {
    year: "2035",
    title: "Space Manufacturing",
    summary: "Orbital factories produce unique materials and products.",
    importance: "Microgravity unlocks new physics for industry.",
    economic: "High-margin materials, pharmaceuticals, and semiconductor processes.",
    tech: ["Orbital platforms", "Autonomous factories", "Return vehicles"],
  },
  {
    year: "2045",
    title: "Lunar Economy",
    summary: "Bases, mining, and cislunar logistics.",
    importance: "Moon becomes an economic node, not only a destination.",
    economic: "Propellant depots, construction, tourism, and science services.",
    tech: ["ISRU", "Lunar landers", "Surface power"],
  },
  {
    year: "2055",
    title: "Mars Colonies",
    summary: "Sustained settlement and interplanetary industry.",
    importance: "Multi-planet civilization begins.",
    economic: "Interplanetary transport, habitats, energy, and terraforming R&D.",
    tech: ["Nuclear propulsion concepts", "Closed ecosystems", "Mars ISRU"],
  },
] as const

export const INDUSTRIES = [
  { id: "launch", title: "Launch Systems", blurb: "Access to orbit — the toll road of the space economy.", detail: "Reusable rockets, small launchers, and heavy-lift vehicles determine cost-per-kg and cadence for every other industry." },
  { id: "sats", title: "Satellites", blurb: "The workhorses of modern orbit.", detail: "Communication, navigation, weather, and science platforms — from cubesats to flagship observatories." },
  { id: "eo", title: "Earth Observation", blurb: "Seeing Earth in high resolution, every day.", detail: "Climate, agriculture, insurance, and defense rely on EO data pipelines and AI analytics." },
  { id: "nav", title: "Navigation", blurb: "Positioning as global infrastructure.", detail: "GNSS underpins logistics, finance timestamps, phones, and autonomous systems." },
  { id: "ai", title: "AI in Space", blurb: "Autonomy beyond the light-delay horizon.", detail: "Onboard AI for guidance, anomaly detection, Earth analytics, and mission planning." },
  { id: "quantum", title: "Quantum Computing", blurb: "Secure links and ultra-hard optimization.", detail: "Quantum-safe communications and simulation for materials, propulsion, and cryptography." },
  { id: "robotics", title: "Space Robotics", blurb: "Hands and eyes where humans cannot go.", detail: "Servicing, assembly, exploration rovers, and dexterous manipulators." },
  { id: "mining", title: "Space Mining", blurb: "Resources beyond Earth.", detail: "Water ice, metals, and propellant feedstock from Moon and asteroids." },
  { id: "lunar", title: "Lunar Construction", blurb: "Building on another world.", detail: "Regolith 3D printing, habitats, landing pads, and power grids." },
  { id: "mars", title: "Mars Colonization", blurb: "Long-horizon settlement industry.", detail: "Transport, life support, energy, and local manufacturing for multi-year missions." },
  { id: "tourism", title: "Space Tourism", blurb: "Experience economy above the Karman line.", detail: "Suborbital flights, orbital hotels, and eventually lunar tourism." },
  { id: "asteroid", title: "Asteroid Mining", blurb: "Prospecting the belt.", detail: "Rare metals and volatiles with extreme logistics challenges — and extreme upside." },
  { id: "orbital-mfg", title: "Orbital Manufacturing", blurb: "Factories in freefall.", detail: "Fiber optics, crystals, alloys, and bioprinting unique to microgravity." },
  { id: "internet", title: "Space Internet", blurb: "Global broadband from LEO.", detail: "Constellations bridging the digital divide and enabling maritime/aviation links." },
  { id: "comms", title: "Deep Space Communication", blurb: "Talking across the solar system.", detail: "Optical links, relay networks, and delay-tolerant networking." },
] as const

export const ECOSYSTEM_NODES = [
  { id: "ai", label: "AI", how: "AI flies missions, processes EO data, and designs next-gen spacecraft." },
  { id: "quantum", label: "Quantum Computing", how: "Secure space links and simulation of materials/propulsion." },
  { id: "robotics", label: "Robotics", how: "Assembly, mining, and exploration without constant human presence." },
  { id: "semi", label: "Semiconductors", how: "Radiation-hardened chips and orbital fab research." },
  { id: "defense", label: "Defense", how: "SSA, secure comms, and resilient PNT infrastructure." },
  { id: "climate", label: "Climate", how: "Satellites measure Earth systems at planetary scale." },
  { id: "telecom", label: "Telecommunications", how: "LEO/MEO constellations redefine connectivity." },
  { id: "medicine", label: "Medicine", how: "Microgravity biology and telemedicine for deep space." },
  { id: "agri", label: "Agriculture", how: "EO + AI optimize yields and water use." },
  { id: "energy", label: "Energy", how: "Space solar concepts and Earth energy monitoring." },
  { id: "edu", label: "Education", how: "Immersive STEM and mission-based learning." },
  { id: "finance", label: "Finance", how: "New asset classes, insurance, and space venture markets." },
  { id: "mfg", label: "Manufacturing", how: "Orbital production and advanced terrestrial spinoffs." },
] as const

export const MISSIONS = [
  { id: "moon", name: "Moon", purpose: "Science outpost + economic foothold in cislunar space.", tech: ["Landers", "ISRU", "Surface power"], challenges: ["Dust", "Thermal extremes", "Logistics"], opportunity: "Bases, mining, tourism, and propellant depots.", careers: ["Lunar systems engineer", "ISRU specialist", "Mission planner"] },
  { id: "mars", name: "Mars", purpose: "Exploration toward sustained presence.", tech: ["Entry descent landing", "Habitats", "Nuclear power concepts"], challenges: ["Distance", "Dust storms", "Life support"], opportunity: "Transport, settlement tech, science services.", careers: ["Propulsion engineer", "Astrobiologist", "Habitat architect"] },
  { id: "europa", name: "Europa", purpose: "Ocean world science under ice.", tech: ["Radiation-hard probes", "Ice penetration concepts"], challenges: ["Jupiter radiation", "Communication delay"], opportunity: "Flagship science + deep-space tech spinoffs.", careers: ["Planetary scientist", "Radiation engineer"] },
  { id: "titan", name: "Titan", purpose: "Organic chemistry lab of the outer system.", tech: ["Rotorscraft", "Cryogenic systems"], challenges: ["Cold", "Atmosphere", "Distance"], opportunity: "Extreme-environment robotics markets.", careers: ["Robotics engineer", "Atmospheric scientist"] },
  { id: "belt", name: "Asteroid Belt", purpose: "Resource prospecting and sample return.", tech: ["Prospecting craft", "Capture systems"], challenges: ["Low gravity", "Autonomy"], opportunity: "Metals and volatiles for space industry.", careers: ["Mining systems engineer", "Autonomy AI"] },
  { id: "stations", name: "Space Stations", purpose: "Persistent platforms for research and industry.", tech: ["Modules", "Life support", "Docking"], challenges: ["Cost", "Debris", "Crew safety"], opportunity: "Commercial LEO destinations.", careers: ["Station ops", "Life support engineer"] },
  { id: "factories", name: "Orbital Factories", purpose: "Produce what Earth gravity prevents.", tech: ["Automation", "Thermal control", "Return"], challenges: ["Reliability", "Downmass"], opportunity: "Premium materials and pharma.", careers: ["Orbital manufacturing eng.", "Process AI"] },
  { id: "solar", name: "Space Solar Farms", purpose: "Collect solar power in orbit.", tech: ["Large structures", "Wireless power concepts"], challenges: ["Assembly", "Transmission"], opportunity: "Clean energy megaprojects.", careers: ["Structures engineer", "Power systems"] },
] as const

export const CAREERS = [
  { title: "Satellite Engineer", skills: ["RF", "ADCS", "Systems"], roadmap: ["Electronics → Orbital mech → CubeSat project"], demand: "Very High", industries: ["Satcom", "EO", "Defense"] },
  { title: "Mission Planner", skills: ["Astrodynamics", "Ops", "Software"], roadmap: ["Physics → Trajectory design → Ops internship"], demand: "High", industries: ["Launch", "Agencies", "Startups"] },
  { title: "Space Lawyer", skills: ["Policy", "Treaties", "Contracts"], roadmap: ["Law + STEM literacy → Space policy"], demand: "Rising", industries: ["Gov", "Commercial", "Insurance"] },
  { title: "Astrobiologist", skills: ["Biology", "Chemistry", "Planetary sci"], roadmap: ["Life sciences → Lab research → Mission science"], demand: "Specialized", industries: ["Science", "Agencies"] },
  { title: "Launch Engineer", skills: ["Propulsion", "Structures", "Test"], roadmap: ["Aero/Mech → Propulsion lab → Launch provider"], demand: "Very High", industries: ["Launch"] },
  { title: "Orbital Architect", skills: ["CAD", "Systems", "Habitats"], roadmap: ["Architecture/Eng → Space systems studio"], demand: "Emerging", industries: ["Stations", "Lunar"] },
  { title: "AI Scientist", skills: ["ML", "Autonomy", "Data"], roadmap: ["CS/Math → Autonomy projects → Space AI"], demand: "Explosive", industries: ["EO", "Ops", "Robotics"] },
  { title: "Quantum Scientist", skills: ["Quantum info", "Optics", "Crypto"], roadmap: ["Physics → Quantum lab → Space links"], demand: "Emerging", industries: ["Comms", "Security"] },
  { title: "Rocket Propulsion Engineer", skills: ["Thermo", "Fluids", "Combustion"], roadmap: ["Mech/Aero → Engine test → Flight"], demand: "Very High", industries: ["Launch", "Deep space"] },
  { title: "Robotics Engineer", skills: ["Controls", "Mech", "Perception"], roadmap: ["Robotics → Space manipulators"], demand: "High", industries: ["Servicing", "Exploration"] },
  { title: "Space Economist", skills: ["Markets", "Policy", "Modeling"], roadmap: ["Econ + Space literacy → Venture/Gov"], demand: "Rising", industries: ["Finance", "Policy"] },
  { title: "Space Entrepreneur", skills: ["Product", "Fundraising", "Domain"], roadmap: ["Build MVP → Customers → Scale"], demand: "High", industries: ["Startups"] },
] as const

export const SPACE_NUMBERS = [
  { label: "Projected Market Size", value: 1.8, suffix: "T+", prefix: "$", decimals: 1 },
  { label: "Commercial Satellites", value: 10000, suffix: "+", prefix: "", decimals: 0 },
  { label: "Annual Rocket Launches", value: 200, suffix: "+", prefix: "", decimals: 0 },
  { label: "Countries in Space", value: 80, suffix: "+", prefix: "", decimals: 0 },
  { label: "Private Companies", value: 10000, suffix: "+", prefix: "", decimals: 0 },
  { label: "Space Startups", value: 2000, suffix: "+", prefix: "", decimals: 0 },
  { label: "Annual Investment", value: 50, suffix: "B+", prefix: "$", decimals: 0 },
  { label: "Deep Space Missions", value: 40, suffix: "+", prefix: "", decimals: 0 },
] as const

export const MAP_POINTS = [
  { name: "Cape Canaveral", type: "Launch Site", x: 28, y: 42 },
  { name: "Vandenberg", type: "Launch Site", x: 18, y: 40 },
  { name: "Kourou", type: "Spaceport", x: 38, y: 55 },
  { name: "Baikonur", type: "Spaceport", x: 58, y: 32 },
  { name: "Sriharikota", type: "Launch Site", x: 68, y: 52 },
  { name: "Tanegashima", type: "Launch Site", x: 82, y: 42 },
  { name: "NASA", type: "Agency", x: 24, y: 38 },
  { name: "ESA", type: "Agency", x: 48, y: 34 },
  { name: "ISRO", type: "Agency", x: 66, y: 48 },
  { name: "JAXA", type: "Agency", x: 84, y: 40 },
  { name: "CNSA", type: "Agency", x: 74, y: 38 },
] as const

export const TECH_LAB = [
  { title: "Rocket Engines", body: "Chemical propulsion from kerolox to methalox — thrust, Isp, and reusability trade-offs." },
  { title: "Ion Thrusters", body: "Electric propulsion for efficient station-keeping and deep-space cruise." },
  { title: "Fusion Concepts", body: "Long-horizon concepts for high-Isp crewed exploration." },
  { title: "Reusable Rockets", body: "Landing, refurbishment, and flight cadence economics." },
  { title: "AI Guidance", body: "Autonomous landing, rendezvous, and anomaly response." },
  { title: "Satellite Systems", body: "Power, thermal, ADCS, payloads, and ground segments." },
  { title: "Quantum Communication", body: "Entanglement and QKD experiments toward secure space links." },
  { title: "Space Manufacturing", body: "Microgravity processes that rewrite materials science." },
] as const

export const AI_PROMPTS = [
  "Explain Orbital Mechanics",
  "How Satellites Work",
  "Space Business Models",
  "Rocket Science Basics",
  "Space Physics Essentials",
  "Space Careers Path",
] as const

export const AI_ANSWERS: Record<string, string> = {
  "Explain Orbital Mechanics":
    "Orbits are free-fall paths balanced by gravity and velocity. LEO (~200–2000 km) offers low latency; GEO (~36,000 km) stays fixed over Earth. Delta-v is the currency of maneuvers — every transfer costs propellant and time.",
  "How Satellites Work":
    "A satellite is a system of power, thermal, computers, attitude control, radios, and payload. Ground stations uplink commands and downlink data. Constellations coordinate coverage like a mesh network in the sky.",
  "Space Business Models":
    "Launch sells access. Satcom and EO sell data/services. In-orbit servicing sells lifetime extension. Tourism sells experience. The winning models productize recurring services, not one-off rockets.",
  "Rocket Science Basics":
    "Thrust overcomes weight; Isp measures efficiency. Staging discards mass. Reuse amortizes hardware cost. Structures must survive aero loads, vibration, and thermal extremes.",
  "Space Physics Essentials":
    "Vacuum, radiation, microgravity, and extreme temperatures dominate design. Orbital debris and plasma environments shape shielding and operations.",
  "Space Careers Path":
    "Build fundamentals (math, physics, coding), ship projects (rockets, cubesats, robotics), then specialize (propulsion, AI, systems, policy). Quantrion Career AI can map your learning profile to roles.",
}

export const NEWS = [
  { id: "1", cat: "Launches", title: "Record cadence quarter for commercial launch", excerpt: "Providers push weekly flights as constellation deployments accelerate." },
  { id: "2", cat: "Science", title: "Ice mapping advances lunar ISRU planning", excerpt: "New analyses refine where water ice may support propellant production." },
  { id: "3", cat: "Technology", title: "Optical intersat links hit new reliability", excerpt: "Laser crosslinks shrink latency for mega-constellations." },
  { id: "4", cat: "Startups", title: "Orbital factory demo produces specialty fiber", excerpt: "Microgravity manufacturing takes another commercial step." },
  { id: "5", cat: "Investment", title: "Space venture funding concentrates on infra", excerpt: "Investors favor launch, sat services, and autonomy stacks." },
  { id: "6", cat: "Moon", title: "Commercial lander window opens", excerpt: "CLPS-style missions expand science and tech demonstration." },
  { id: "7", cat: "Mars", title: "Sample return architecture studies update", excerpt: "Agencies refine multi-element Mars logistics concepts." },
  { id: "8", cat: "Satellites", title: "Earth observation AI cuts disaster response time", excerpt: "Models flag floods and fires hours faster." },
  { id: "9", cat: "Space Policy", title: "Debris mitigation norms tighten", excerpt: "Operators face stronger end-of-life and SSA expectations." },
  { id: "10", cat: "Deep Space", title: "Outer planets probe concepts advance", excerpt: "Power and comms breakthroughs unlock ice-giant science." },
] as const

export const NEWS_CATS = [
  "All",
  "Launches",
  "Science",
  "Technology",
  "Startups",
  "Investment",
  "Moon",
  "Mars",
  "Satellites",
  "Space Policy",
  "Deep Space",
] as const

export const FUTURE_STAGES = [
  { id: "earth", title: "Today's Earth", body: "Space already powers GPS, weather, internet, and defense — invisible infrastructure." },
  { id: "moon", title: "Moon Bases", body: "Outposts for science, tourism, and propellant — the first off-world economy." },
  { id: "orbital", title: "Orbital Cities", body: "Stations become towns: labs, factories, hotels, and shipyards in LEO." },
  { id: "asteroid", title: "Asteroid Mining", body: "Resources flow inward; industry expands beyond Earth's gravity well." },
  { id: "mars", title: "Mars Civilization", body: "Settlements demand energy, food, medicine, law, and local industry." },
  { id: "interplanetary", title: "Interplanetary Economy", body: "Trade routes across the solar system — humanity's multi-world market." },
] as const

export const SPACE_PROJECT_CATS = [
  "All",
  "Rockets",
  "Shuttles",
  "Satellites",
  "Stations",
  "Probes",
  "Landers",
  "Rovers",
  "Telescopes",
  "Habitats",
] as const

export const SPACE_PROJECTS = [
  {
    id: "saturn-v",
    cat: "Rockets",
    name: "Saturn V",
    era: "1967–1973",
    status: "Historic",
    summary: "The heavy-lift rocket that carried Apollo crews to the Moon.",
    build: "Three stages, F-1 and J-2 engines, unmatched thrust for its era.",
    impact: "Proved crewed lunar capability and systems engineering at planetary scale.",
  },
  {
    id: "falcon-9",
    cat: "Rockets",
    name: "Falcon 9",
    era: "2010–Present",
    status: "Active",
    summary: "The workhorse reusable orbital launcher of the commercial era.",
    build: "Nine Merlin engines, propulsive first-stage landing, rapid reuse.",
    impact: "Collapsed launch cost and enabled mega-constellation cadence.",
  },
  {
    id: "sls",
    cat: "Rockets",
    name: "Space Launch System",
    era: "2022–Present",
    status: "Active",
    summary: "NASA's deep-space heavy lifter for Artemis lunar missions.",
    build: "Core stage + solid boosters derived from shuttle heritage.",
    impact: "Enables Orion crew flights and lunar exploration logistics.",
  },
  {
    id: "starship",
    cat: "Rockets",
    name: "Starship",
    era: "Flight test era",
    status: "Development",
    summary: "Fully reusable super-heavy vehicle aimed at Moon, Mars, and point-to-point.",
    build: "Stainless steel tanks, Raptor methalox engines, ship + booster stack.",
    impact: "Potential step-change in payload mass and interplanetary transport.",
  },
  {
    id: "pslv",
    cat: "Rockets",
    name: "PSLV",
    era: "1993–Present",
    status: "Active",
    summary: "ISRO's reliable polar satellite launch vehicle.",
    build: "Four-stage solid/liquid mix optimized for sun-synchronous orbits.",
    impact: "Powered India's EO and science missions plus commercial rideshares.",
  },
  {
    id: "space-shuttle",
    cat: "Shuttles",
    name: "Space Shuttle Orbiter",
    era: "1981–2011",
    status: "Historic",
    summary: "Reusable winged spacecraft for crew and cargo to low Earth orbit.",
    build: "Orbiter + external tank + twin solid rocket boosters.",
    impact: "Built ISS modules, deployed Hubble, and trained a generation of ops.",
  },
  {
    id: "buran",
    cat: "Shuttles",
    name: "Buran",
    era: "1988",
    status: "Historic",
    summary: "Soviet reusable orbiter program with autonomous landing capability.",
    build: "Orbiter launched atop Energia heavy-lift rocket.",
    impact: "Demonstrated alternate reusable architecture and auto-landing.",
  },
  {
    id: "dream-chaser",
    cat: "Shuttles",
    name: "Dream Chaser",
    era: "Commercial cargo era",
    status: "Development",
    summary: "Lifting-body reusable spaceplane for ISS cargo and future crew concepts.",
    build: "Runway landing, composite structure, cargo variant first.",
    impact: "Brings runway-return flexibility to commercial LEO logistics.",
  },
  {
    id: "hubble",
    cat: "Telescopes",
    name: "Hubble Space Telescope",
    era: "1990–Present",
    status: "Active",
    summary: "Iconic optical observatory that reshaped modern astronomy.",
    build: "2.4 m mirror, serviceable instruments, LEO vantage above atmosphere.",
    impact: "Deep-field cosmology, exoplanet atmospheres, public science culture.",
  },
  {
    id: "jwst",
    cat: "Telescopes",
    name: "James Webb Space Telescope",
    era: "2021–Present",
    status: "Active",
    summary: "Infrared flagship observatory at Sun–Earth L2.",
    build: "6.5 m segmented mirror, sunshield, cryogenic instruments.",
    impact: "Early universe galaxies, exoplanet chemistry, star-forming regions.",
  },
  {
    id: "gps",
    cat: "Satellites",
    name: "GPS Constellation",
    era: "1978–Present",
    status: "Active",
    summary: "Global navigation satellites underpinning modern positioning.",
    build: "MEO constellation with precise atomic clocks and ranging signals.",
    impact: "Logistics, finance timestamps, phones, aviation, and autonomy.",
  },
  {
    id: "starlink",
    cat: "Satellites",
    name: "Starlink",
    era: "2019–Present",
    status: "Active",
    summary: "LEO broadband mega-constellation for global internet.",
    build: "Mass-produced small sats with phased arrays and optical links.",
    impact: "Connectivity for remote regions, maritime, aviation, and resilience.",
  },
  {
    id: "cubesat",
    cat: "Satellites",
    name: "CubeSat Platforms",
    era: "1999–Present",
    status: "Active",
    summary: "Standardized small satellites that democratized space access.",
    build: "1U–12U modular buses, rideshare launches, open standards.",
    impact: "University missions, startups, and rapid tech demonstration.",
  },
  {
    id: "landsat",
    cat: "Satellites",
    name: "Landsat Series",
    era: "1972–Present",
    status: "Active",
    summary: "Longest continuous Earth observation record from space.",
    build: "Multispectral imagers for land cover and resource monitoring.",
    impact: "Agriculture, climate science, disaster response, and open data.",
  },
  {
    id: "iss",
    cat: "Stations",
    name: "International Space Station",
    era: "1998–Present",
    status: "Active",
    summary: "Humanity's continuous laboratory and home in low Earth orbit.",
    build: "Modular pressurized segments, solar arrays, docking ports.",
    impact: "Microgravity science, international ops, and commercial LEO pathfinding.",
  },
  {
    id: "tiangong",
    cat: "Stations",
    name: "Tiangong",
    era: "2021–Present",
    status: "Active",
    summary: "China's modular crewed space station.",
    build: "Core module + science labs with visiting craft support.",
    impact: "Independent long-duration human presence and research.",
  },
  {
    id: "skylab",
    cat: "Stations",
    name: "Skylab",
    era: "1973–1979",
    status: "Historic",
    summary: "America's first space station — solar science and habitability labs.",
    build: "Converted Saturn upper stage into orbital workshop.",
    impact: "Lessons for long-duration crew health and station ops.",
  },
  {
    id: "gateway",
    cat: "Stations",
    name: "Lunar Gateway",
    era: "Artemis era",
    status: "Development",
    summary: "Cislunar outpost supporting lunar surface missions.",
    build: "Power & propulsion, habitation, and logistics modules in NRHO.",
    impact: "Staging point for Moon science, ISRU demos, and deep-space ops.",
  },
  {
    id: "voyager",
    cat: "Probes",
    name: "Voyager 1 & 2",
    era: "1977–Present",
    status: "Active",
    summary: "Interstellar ambassadors that redefined the outer solar system.",
    build: "RTG-powered probes with gravity-assist grand tour design.",
    impact: "Planetary flybys, heliopause science, and deep-space longevity.",
  },
  {
    id: "curiosity",
    cat: "Rovers",
    name: "Curiosity Rover",
    era: "2012–Present",
    status: "Active",
    summary: "Car-sized Mars Science Laboratory exploring Gale Crater.",
    build: "Nuclear RTG, robotic arm, chemistry and imaging suite.",
    impact: "Habitability evidence and long-lived Mars surface ops.",
  },
  {
    id: "perseverance",
    cat: "Rovers",
    name: "Perseverance + Ingenuity",
    era: "2021–Present",
    status: "Active",
    summary: "Sample-caching Mars rover with the first powered aircraft on another world.",
    build: "Auto-nav, MOXIE oxygen demo, helicopter tech pathfinder.",
    impact: "Sample return prep and aerial exploration breakthrough.",
  },
  {
    id: "apollo-lm",
    cat: "Landers",
    name: "Apollo Lunar Module",
    era: "1969–1972",
    status: "Historic",
    summary: "The first crewed lander to touch another world.",
    build: "Ascent/descent stages, lightweight structure, abort modes.",
    impact: "Template for future human landing systems.",
  },
  {
    id: "viking",
    cat: "Landers",
    name: "Viking Landers",
    era: "1976",
    status: "Historic",
    summary: "First successful soft landings and biology experiments on Mars.",
    build: "Stereo cameras, soil samplers, weather and chemistry labs.",
    impact: "Foundation of Mars surface science and landing engineering.",
  },
  {
    id: "chandrayaan-lander",
    cat: "Landers",
    name: "Chandrayaan Landers",
    era: "2019–Present",
    status: "Active",
    summary: "ISRO lunar landing and rover missions including near-south-pole success.",
    build: "Soft-landing propulsion, Vikram lander + Pragyan rover architecture.",
    impact: "Expanded global lunar access and polar science interest.",
  },
  {
    id: "orbital-habitat",
    cat: "Habitats",
    name: "Commercial Orbital Habitats",
    era: "2020s–2030s",
    status: "Development",
    summary: "Private stations and modules for research, tourism, and manufacturing.",
    build: "Inflatable and rigid modules, docking standards, life support.",
    impact: "Successor economy to ISS in commercial LEO.",
  },
  {
    id: "lunar-base",
    cat: "Habitats",
    name: "Lunar Base Concepts",
    era: "2030s horizon",
    status: "Concept",
    summary: "Surface habitats for science, ISRU, and sustained lunar presence.",
    build: "Regolith shielding, power systems, pressurized living volumes.",
    impact: "First permanent economic foothold beyond Earth orbit.",
  },
  {
    id: "mars-habitat",
    cat: "Habitats",
    name: "Mars Habitat Systems",
    era: "Long-horizon",
    status: "Concept",
    summary: "Closed-loop living systems for multi-year Mars surface stays.",
    build: "Life support, radiation protection, local resource integration.",
    impact: "Enables settlement industry and interplanetary civilization.",
  },
] as const
