export type ExamCategory = {
  id: string
  emoji: string
  title: string
  region: string
  blurb: string
  exams: readonly { name: string; detail: string }[]
}

export const EXAM_CATALOG: readonly ExamCategory[] = [
  {
    id: "india-engg-med",
    emoji: "🇮🇳",
    title: "India · Engineering & Medical",
    region: "India",
    blurb: "The highest-volume STEM entrance pathways in India.",
    exams: [
      { name: "JEE Main", detail: "Engineering entrance · NTA" },
      { name: "JEE Advanced", detail: "IIT admission gateway" },
      { name: "NEET-UG", detail: "Medical & dental entrance" },
      { name: "BITSAT", detail: "BITS Pilani admissions" },
      { name: "VITEEE", detail: "VIT engineering entrance" },
      { name: "SRMJEEE", detail: "SRM engineering entrance" },
      { name: "COMEDK UGET", detail: "Karnataka private engg" },
      { name: "MHT CET", detail: "Maharashtra CET" },
      { name: "WBJEE", detail: "West Bengal JEE" },
      { name: "KEAM", detail: "Kerala engineering/medical" },
      { name: "AIIMS INI-CET", detail: "PG medical institutes" },
      { name: "NEET-PG", detail: "Postgraduate medical" },
    ],
  },
  {
    id: "india-govt",
    emoji: "🏛",
    title: "India · Civil Services & Government",
    region: "India",
    blurb: "National and state services that millions prepare for yearly.",
    exams: [
      { name: "UPSC CSE", detail: "Civil Services Exam" },
      { name: "UPSC CDS", detail: "Combined Defence Services" },
      { name: "UPSC NDA", detail: "National Defence Academy" },
      { name: "UPSC CAPF", detail: "Central Armed Police Forces" },
      { name: "UPSC IES/ESE", detail: "Engineering Services" },
      { name: "SSC CGL", detail: "Combined Graduate Level" },
      { name: "SSC CHSL", detail: "Higher Secondary Level" },
      { name: "SSC GD", detail: "General Duty Constable" },
      { name: "IBPS PO", detail: "Bank Probationary Officer" },
      { name: "IBPS Clerk", detail: "Bank clerical cadre" },
      { name: "SBI PO", detail: "State Bank of India PO" },
      { name: "RBI Grade B", detail: "Reserve Bank officers" },
      { name: "NABARD Grade A", detail: "Development banking" },
      { name: "State PSC", detail: "State civil services" },
      { name: "Railway RRB NTPC", detail: "Railway recruitment" },
      { name: "Railway RRB JE", detail: "Junior Engineer" },
    ],
  },
  {
    id: "india-mgmt-law",
    emoji: "📊",
    title: "India · Management, Law & Design",
    region: "India",
    blurb: "MBA, law, and design entrances with national prestige.",
    exams: [
      { name: "CAT", detail: "IIMs & top MBA programs" },
      { name: "XAT", detail: "XLRI & associates" },
      { name: "SNAP", detail: "Symbiosis MBA" },
      { name: "NMAT", detail: "NMIMS & partners" },
      { name: "MAT", detail: "Management Aptitude Test" },
      { name: "CMAT", detail: "AICTE management test" },
      { name: "CLAT", detail: "National Law Universities" },
      { name: "AILET", detail: "NLU Delhi" },
      { name: "LSAT—India", detail: "Law School Admission Test" },
      { name: "NID DAT", detail: "National Institute of Design" },
      { name: "NIFT", detail: "Fashion technology" },
      { name: "UCEED", detail: "IIT design entrance" },
      { name: "CEED", detail: "PG design entrance" },
    ],
  },
  {
    id: "india-pg-research",
    emoji: "🔬",
    title: "India · GATE, NET & Research",
    region: "India",
    blurb: "Postgraduate engineering, teaching, and research pathways.",
    exams: [
      { name: "GATE", detail: "MTech / PSU gateway" },
      { name: "UGC NET", detail: "Assistant Professor / JRF" },
      { name: "CSIR NET", detail: "Science research fellowship" },
      { name: "ICAR AIEEA", detail: "Agriculture education" },
      { name: "CUET-UG", detail: "Central universities UG" },
      { name: "CUET-PG", detail: "Central universities PG" },
      { name: "IIT JAM", detail: "MSc at IITs" },
      { name: "TIFR GS", detail: "TIFR graduate school" },
      { name: "NBHM", detail: "Mathematics scholarship" },
      { name: "NEST", detail: "NISER / UM-DAE CEBS" },
    ],
  },
  {
    id: "india-teaching-defence",
    emoji: "🛡",
    title: "India · Teaching & Defence",
    region: "India",
    blurb: "Teacher eligibility and defence academy pathways.",
    exams: [
      { name: "CTET", detail: "Central Teacher Eligibility" },
      { name: "State TET", detail: "State teacher eligibility" },
      { name: "KVS / NVS", detail: "Central school teaching" },
      { name: "AFCAT", detail: "Air Force Common Admission" },
      { name: "INET", detail: "Indian Navy Entrance" },
      { name: "TES / TGC", detail: "Army technical entries" },
    ],
  },
  {
    id: "us-undergrad",
    emoji: "🇺🇸",
    title: "USA · Undergraduate Admissions",
    region: "United States",
    blurb: "College admissions tests used by millions globally each year.",
    exams: [
      { name: "SAT", detail: "College Board admissions" },
      { name: "ACT", detail: "US college admissions" },
      { name: "AP Exams", detail: "Advanced Placement" },
      { name: "PSAT / NMSQT", detail: "Practice & scholarships" },
      { name: "CLEP", detail: "College-Level Examination" },
    ],
  },
  {
    id: "us-grad",
    emoji: "🎓",
    title: "USA · Graduate & Professional",
    region: "United States",
    blurb: "Graduate school and licensed professional pathways.",
    exams: [
      { name: "GRE General", detail: "Graduate admissions" },
      { name: "GRE Subject", detail: "Subject graduate tests" },
      { name: "GMAT Focus", detail: "MBA admissions" },
      { name: "LSAT", detail: "Law school admissions" },
      { name: "MCAT", detail: "Medical school admissions" },
      { name: "DAT", detail: "Dental admissions" },
      { name: "OAT", detail: "Optometry admissions" },
      { name: "PCAT", detail: "Pharmacy admissions" },
      { name: "USMLE", detail: "US medical licensing" },
      { name: "COMLEX", detail: "Osteopathic licensing" },
      { name: "Bar Exam (UBE)", detail: "US attorney licensing" },
      { name: "CPA Exam", detail: "Certified Public Accountant" },
    ],
  },
  {
    id: "english",
    emoji: "🌐",
    title: "English Language Proficiency",
    region: "Global",
    blurb: "Global English tests for study, work, and migration.",
    exams: [
      { name: "IELTS Academic", detail: "Study abroad standard" },
      { name: "IELTS General", detail: "Migration & work" },
      { name: "TOEFL iBT", detail: "US/global university English" },
      { name: "PTE Academic", detail: "Pearson English test" },
      { name: "Duolingo English Test", detail: "Online English admissions" },
      { name: "Cambridge C1 Advanced", detail: "CAE proficiency" },
      { name: "Cambridge C2 Proficiency", detail: "CPE mastery" },
      { name: "OET", detail: "Healthcare English" },
      { name: "CELPIP", detail: "Canadian English" },
      { name: "TOEIC", detail: "Workplace English" },
    ],
  },
  {
    id: "uk-eu",
    emoji: "🇬🇧",
    title: "UK · Europe Admissions",
    region: "UK & Europe",
    blurb: "High-stakes UK and European university entrance assessments.",
    exams: [
      { name: "UCAT", detail: "UK clinical aptitude" },
      { name: "BMAT", detail: "Biomedical admissions (legacy/select)" },
      { name: "LNAT", detail: "UK law admissions" },
      { name: "TMUA", detail: "Maths admissions" },
      { name: "MAT (Oxford)", detail: "Oxford mathematics" },
      { name: "PAT (Oxford)", detail: "Physics aptitude" },
      { name: "TSA", detail: "Thinking Skills Assessment" },
      { name: "STEP", detail: "Cambridge maths" },
      { name: "ESAT", detail: "Engineering & science admissions" },
      { name: "HAT", detail: "History aptitude" },
      { name: "PLAB", detail: "UK medical licensing" },
      { name: "MRCP", detail: "UK physician membership" },
    ],
  },
  {
    id: "china-asia",
    emoji: "🌏",
    title: "Asia · National Gateways",
    region: "Asia",
    blurb: "Major Asian national exams that define annual student cohorts.",
    exams: [
      { name: "Gaokao", detail: "China national college entrance" },
      { name: "CSAT (Suneung)", detail: "South Korea CSAT" },
      { name: "Center Test / Common Test", detail: "Japan university admissions" },
      { name: "NTU / GSAT tracks", detail: "Taiwan admissions pathways" },
      { name: "SNBT / UTBK", detail: "Indonesia university entrance" },
      { name: "TNHEE", detail: "Thailand national exams" },
      { name: "HKDSE", detail: "Hong Kong Diploma" },
      { name: "A-Levels", detail: "UK-style advanced levels (global)" },
      { name: "IB Diploma", detail: "International Baccalaureate" },
    ],
  },
  {
    id: "finance-pro",
    emoji: "💼",
    title: "Finance & Professional Credentials",
    region: "Global",
    blurb: "World-recognized finance and accounting credentials.",
    exams: [
      { name: "CFA Level I–III", detail: "Chartered Financial Analyst" },
      { name: "FRM Part I–II", detail: "Financial Risk Manager" },
      { name: "ACCA", detail: "Association of Chartered Accountants" },
      { name: "CA (India)", detail: "Chartered Accountancy" },
      { name: "CMA (US)", detail: "Certified Management Accountant" },
      { name: "CIA", detail: "Certified Internal Auditor" },
      { name: "CFP", detail: "Certified Financial Planner" },
      { name: "CAIA", detail: "Alternative Investment Analyst" },
      { name: "SOA / CAS Actuarial", detail: "Actuarial exams" },
      { name: "SEBI Grade A", detail: "India securities regulator" },
    ],
  },
  {
    id: "tech-cloud",
    emoji: "☁️",
    title: "Technology & Cloud Certifications",
    region: "Global",
    blurb: "Industry certifications that shape tech careers worldwide.",
    exams: [
      { name: "AWS Solutions Architect", detail: "Amazon Web Services" },
      { name: "AWS Developer / SysOps", detail: "AWS associate tracks" },
      { name: "Google Cloud Professional", detail: "GCP certifications" },
      { name: "Azure Administrator", detail: "Microsoft Azure" },
      { name: "Azure Solutions Architect", detail: "Azure expert path" },
      { name: "Cisco CCNA", detail: "Networking foundation" },
      { name: "Cisco CCNP", detail: "Professional networking" },
      { name: "CompTIA Security+", detail: "Cybersecurity baseline" },
      { name: "CompTIA Network+", detail: "Networking baseline" },
      { name: "Certified Kubernetes (CKA)", detail: "Cloud native ops" },
      { name: "PMP", detail: "Project Management Professional" },
      { name: "ITIL 4", detail: "IT service management" },
    ],
  },
  {
    id: "medical-global",
    emoji: "🩺",
    title: "Global Medical Licensing",
    region: "Global",
    blurb: "Licensing exams that unlock practice across countries.",
    exams: [
      { name: "USMLE Step 1–3", detail: "US medical licensing" },
      { name: "PLAB 1–2", detail: "UK medical licensing" },
      { name: "FMGE / NExT", detail: "India foreign medical graduate" },
      { name: "AMC (Australia)", detail: "Australian medical council" },
      { name: "MCCQE (Canada)", detail: "Canadian medical qualifying" },
      { name: "NZREX", detail: "New Zealand medical" },
      { name: "DHA / MOH / HAAD", detail: "UAE health licensing" },
      { name: "Prometric (SCFHS)", detail: "Saudi health licensing" },
    ],
  },
  {
    id: "languages",
    emoji: "🗣",
    title: "World Language Exams",
    region: "Global",
    blurb: "Language certifications for study, careers, and immigration.",
    exams: [
      { name: "DELF / DALF", detail: "French proficiency" },
      { name: "TCF / TEF", detail: "French immigration/academic" },
      { name: "Goethe-Zertifikat", detail: "German proficiency" },
      { name: "TestDaF", detail: "German academic" },
      { name: "DELE", detail: "Spanish proficiency" },
      { name: "SIELE", detail: "Spanish online" },
      { name: "HSK", detail: "Chinese proficiency" },
      { name: "JLPT", detail: "Japanese Language Proficiency" },
      { name: "TOPIK", detail: "Korean proficiency" },
      { name: "CELI / CILS", detail: "Italian proficiency" },
    ],
  },
  {
    id: "olympiads",
    emoji: "🏆",
    title: "Olympiads & Talent Search",
    region: "Global",
    blurb: "Elite academic competitions students train for year-round.",
    exams: [
      { name: "IMO", detail: "International Mathematical Olympiad" },
      { name: "IOI", detail: "International Olympiad in Informatics" },
      { name: "IPhO", detail: "International Physics Olympiad" },
      { name: "IChO", detail: "International Chemistry Olympiad" },
      { name: "IBO", detail: "International Biology Olympiad" },
      { name: "IOAA", detail: "Astronomy & Astrophysics" },
      { name: "IEO / NSEJS pathways", detail: "Science olympiad tracks" },
      { name: "KVPY legacy / INSPIRE", detail: "Science talent pathways" },
      { name: "NTSE", detail: "National Talent Search (India)" },
      { name: "Science Bowl / Mathcounts", detail: "US academic contests" },
    ],
  },
  {
    id: "school-boards",
    emoji: "📚",
    title: "School Boards & Pre-University",
    region: "Global",
    blurb: "Board and pre-university credentials that shape annual cohorts.",
    exams: [
      { name: "CBSE Class 10 / 12", detail: "India national board" },
      { name: "CISCE ISC / ICSE", detail: "India ICSE board" },
      { name: "Cambridge IGCSE", detail: "International secondary" },
      { name: "Cambridge AS / A Levels", detail: "Pre-university" },
      { name: "IB MYP / DP", detail: "International Baccalaureate" },
      { name: "State Boards (India)", detail: "State higher secondary" },
      { name: "GED", detail: "High school equivalency" },
    ],
  },
] as const

export const TOTAL_EXAMS = EXAM_CATALOG.reduce((n, c) => n + c.exams.length, 0)

export const EXAM_REGIONS = [
  "All",
  "India",
  "United States",
  "UK & Europe",
  "Asia",
  "Global",
] as const
