export type CoursePillar = "space" | "industrial"

export type SpaceCourseCategory = {
  id: string
  emoji: string
  title: string
  blurb: string
  pillar: CoursePillar
  courses: readonly string[]
}

export const SPACE_INDUSTRIAL_CATALOG: readonly SpaceCourseCategory[] = [
  {
    id: "foundation",
    emoji: "🚀",
    title: "Foundation",
    blurb: "Origin stories, governance, and the commercial architecture of space.",
    pillar: "space",
    courses: [
      "Introduction to Space Economy",
      "History of Space Exploration",
      "Evolution of Space Technology",
      "Future of Space Civilization",
      "Commercial Space Industry",
      "Space Policy & Governance",
      "Space Law",
      "Ethics of Space Exploration",
      "Global Space Agencies",
      "Space Industry Overview",
    ],
  },
  {
    id: "astronomy",
    emoji: "🌍",
    title: "Astronomy & Space Science",
    blurb: "From stellar physics to deep-space environments.",
    pillar: "space",
    courses: [
      "Astronomy Fundamentals",
      "Astrophysics",
      "Cosmology",
      "Stellar Evolution",
      "Solar System Science",
      "Planetary Science",
      "Exoplanets",
      "Black Holes",
      "Dark Matter",
      "Dark Energy",
      "Galaxies",
      "Nebulae",
      "Space Weather",
      "Solar Physics",
      "Lunar Science",
      "Mars Science",
      "Comets & Asteroids",
      "Meteors",
      "Space Radiation",
      "Deep Space Exploration",
    ],
  },
  {
    id: "rockets",
    emoji: "🚀",
    title: "Rocket Engineering",
    blurb: "Propulsion, structures, launch ops, and flight dynamics.",
    pillar: "space",
    courses: [
      "Rocket Science",
      "Rocket Propulsion",
      "Liquid Engines",
      "Solid Rocket Motors",
      "Hybrid Propulsion",
      "Cryogenic Engines",
      "Electric Propulsion",
      "Ion Thrusters",
      "Nuclear Propulsion",
      "Rocket Structures",
      "Stage Separation",
      "Reusable Rockets",
      "Launch Operations",
      "Flight Dynamics",
      "Mission Planning",
      "Payload Integration",
      "Launch Safety",
      "Spaceport Operations",
    ],
  },
  {
    id: "satellites",
    emoji: "🛰",
    title: "Satellite Engineering",
    blurb: "Design, manufacture, payloads, and deployment of orbital systems.",
    pillar: "space",
    courses: [
      "Satellite Fundamentals",
      "Satellite Design",
      "Satellite Manufacturing",
      "CubeSats",
      "Nano Satellites",
      "Communication Satellites",
      "Earth Observation Satellites",
      "Weather Satellites",
      "Navigation Satellites",
      "Military Satellites",
      "Satellite Electronics",
      "Satellite Payload Systems",
      "Satellite Power Systems",
      "Satellite Thermal Systems",
      "Satellite Testing",
      "Satellite Deployment",
    ],
  },
  {
    id: "comms",
    emoji: "🌐",
    title: "Space Communications",
    blurb: "RF, laser, networks, and the interplanetary internet.",
    pillar: "space",
    courses: [
      "Space Communication Systems",
      "Deep Space Networks",
      "Satellite Internet",
      "RF Communication",
      "Laser Communication",
      "Space Networking",
      "Interplanetary Internet",
    ],
  },
  {
    id: "orbital",
    emoji: "🧭",
    title: "Orbital Mechanics",
    blurb: "Trajectories, attitude, rendezvous, and gravity assists.",
    pillar: "space",
    courses: [
      "Orbital Mechanics",
      "Space Navigation",
      "Orbital Transfers",
      "Spacecraft Attitude Control",
      "Rendezvous & Docking",
      "Mission Trajectory Design",
      "Gravity Assist",
    ],
  },
  {
    id: "ai-robotics",
    emoji: "🤖",
    title: "AI, Robotics & Automation",
    blurb: "Autonomy that operates beyond the light-delay horizon.",
    pillar: "space",
    courses: [
      "AI for Space Missions",
      "Autonomous Spacecraft",
      "Space Robotics",
      "Rover Engineering",
      "Drone Technology for Space",
      "Computer Vision in Space",
      "Autonomous Docking",
      "Intelligent Mission Planning",
      "Predictive Maintenance",
      "Digital Twins for Space",
    ],
  },
  {
    id: "computing",
    emoji: "💻",
    title: "Computing",
    blurb: "Radiation-hard, edge, cloud, and secure space computing.",
    pillar: "space",
    courses: [
      "Embedded Systems",
      "Space Electronics",
      "Radiation-Hardened Computing",
      "High Performance Computing",
      "Cloud Computing for Space",
      "Edge Computing",
      "Cybersecurity for Satellites",
    ],
  },
  {
    id: "quantum",
    emoji: "⚛",
    title: "Quantum Technologies",
    blurb: "Quantum compute, links, sensing, and cryptography for space.",
    pillar: "space",
    courses: [
      "Quantum Computing",
      "Quantum Communication",
      "Quantum Navigation",
      "Quantum Sensors",
      "Quantum Cryptography",
    ],
  },
  {
    id: "earth-obs",
    emoji: "🌍",
    title: "Earth Observation",
    blurb: "Sensing Earth for climate, agriculture, and disaster response.",
    pillar: "space",
    courses: [
      "Remote Sensing",
      "GIS",
      "Climate Monitoring",
      "Agriculture Monitoring",
      "Disaster Management",
      "Ocean Observation",
      "Environmental Analytics",
    ],
  },
  {
    id: "infrastructure",
    emoji: "🏗",
    title: "Space Infrastructure",
    blurb: "Stations, habitats, factories, and in-space assembly.",
    pillar: "space",
    courses: [
      "Space Stations",
      "Lunar Bases",
      "Mars Habitats",
      "Orbital Manufacturing",
      "Space Elevators (Concepts)",
      "Space Construction",
      "In-Space Assembly",
    ],
  },
  {
    id: "resources",
    emoji: "⛏",
    title: "Space Resources",
    blurb: "Mining, ISRU, water, and propellant production off-world.",
    pillar: "space",
    courses: [
      "Asteroid Mining",
      "Lunar Mining",
      "Space Resource Utilization",
      "Rare Metals",
      "Water Extraction",
      "Fuel Production in Space",
    ],
  },
  {
    id: "energy",
    emoji: "☀",
    title: "Space Energy",
    blurb: "Solar, nuclear, and storage systems for space operations.",
    pillar: "space",
    courses: [
      "Space Solar Power",
      "Nuclear Power in Space",
      "Energy Storage",
      "Lunar Energy Systems",
    ],
  },
  {
    id: "medicine",
    emoji: "👨‍⚕",
    title: "Space Medicine",
    blurb: "Human performance, life support, and radiation protection.",
    pillar: "space",
    courses: [
      "Human Spaceflight",
      "Space Physiology",
      "Space Psychology",
      "Space Nutrition",
      "Radiation Protection",
      "Life Support Systems",
    ],
  },
  {
    id: "business",
    emoji: "💰",
    title: "Space Economy & Business",
    blurb: "Markets, startups, capital, insurance, and NewSpace models.",
    pillar: "space",
    courses: [
      "Space Economy",
      "Commercial Space Industry",
      "Space Entrepreneurship",
      "Space Startup Building",
      "Venture Capital in Space",
      "Space Finance",
      "Space Investment",
      "Space Insurance",
      "Satellite Business Models",
      "NewSpace Industry",
    ],
  },
  {
    id: "policy",
    emoji: "⚖",
    title: "Policy & Law",
    blurb: "Treaties, licensing, regulations, and export controls.",
    pillar: "space",
    courses: [
      "International Space Law",
      "Space Treaties",
      "Satellite Regulations",
      "Licensing",
      "Export Controls",
    ],
  },
  {
    id: "defense",
    emoji: "🛡",
    title: "Defense & Security",
    blurb: "Surveillance, warning systems, and national security space.",
    pillar: "space",
    courses: [
      "Space Defense",
      "Space Surveillance",
      "Missile Warning Systems",
      "National Security Space",
      "Space Cybersecurity",
    ],
  },
  {
    id: "moon",
    emoji: "🌕",
    title: "Moon Programs",
    blurb: "Artemis, lunar economy, mining, and habitat engineering.",
    pillar: "space",
    courses: [
      "Artemis Program",
      "Lunar Exploration",
      "Lunar Economy",
      "Moon Mining",
      "Moon Habitat Engineering",
    ],
  },
  {
    id: "mars",
    emoji: "🔴",
    title: "Mars Programs",
    blurb: "Exploration, colonization, agriculture, and Mars industry.",
    pillar: "space",
    courses: [
      "Mars Exploration",
      "Mars Colonization",
      "Mars Agriculture",
      "Mars Infrastructure",
      "Mars Economy",
    ],
  },
  {
    id: "advanced",
    emoji: "🧪",
    title: "Advanced Technologies",
    blurb: "Fusion, nanomaterials, bioengineering, and swarm systems.",
    pillar: "space",
    courses: [
      "Fusion Propulsion",
      "Space Manufacturing",
      "Nanotechnology for Space",
      "Advanced Materials",
      "3D Printing in Space",
      "Bioengineering for Space",
      "Swarm Satellites",
      "Autonomous Space Factories",
    ],
  },
  {
    id: "careers",
    emoji: "📈",
    title: "Careers & Industry",
    blurb: "Agency paths, NewSpace skills, and interview readiness.",
    pillar: "space",
    courses: [
      "Space Career Roadmap",
      "Space Interview Preparation",
      "Satellite Industry Careers",
      "ISRO Career Path",
      "NASA Career Path",
      "ESA Career Path",
      "SpaceX Engineering Skills",
      "Blue Origin Engineering",
      "Rocket Lab Engineering",
      "Startup Careers",
    ],
  },
  {
    id: "research",
    emoji: "🔬",
    title: "Research",
    blurb: "Methodology, papers, simulations, and civilization-scale futures.",
    pillar: "space",
    courses: [
      "Space Research Methodology",
      "Scientific Writing",
      "Research Paper Analysis",
      "Space Simulations",
      "Space Data Analytics",
      "Mission Case Studies",
      "Future Space Technologies",
      "Interstellar Exploration",
      "Space Civilization",
      "Next-Generation Space Economy",
    ],
  },

  // ── Explore Industries · Full multi-industry curriculum ─────────────
  {
    id: "healthcare",
    emoji: "🏥",
    title: "Healthcare & Medical",
    blurb: "Clinical, hospital, and medical-technology pathways for the health economy.",
    pillar: "industrial",
    courses: [
      "MBBS Fundamentals",
      "Nursing",
      "Pharmacy",
      "Dentistry",
      "Physiotherapy",
      "Radiology & Medical Imaging",
      "Laboratory Technology",
      "Public Health",
      "Biomedical Engineering",
      "Hospital Management",
      "Medical Coding & Billing",
      "Telemedicine",
      "Clinical Research",
      "Medical AI",
      "Healthcare Data Analytics",
    ],
  },
  {
    id: "it-ai",
    emoji: "💻",
    title: "Information Technology & AI",
    blurb: "Software, cloud, security, and the full AI stack from code to models.",
    pillar: "industrial",
    courses: [
      "Programming",
      "Data Structures & Algorithms",
      "Web Development",
      "Mobile App Development",
      "Cloud Computing",
      "Cybersecurity",
      "Data Science",
      "Artificial Intelligence",
      "Machine Learning",
      "Deep Learning",
      "Generative AI",
      "DevOps",
      "Software Engineering",
      "Blockchain",
      "Quantum Computing",
    ],
  },
  {
    id: "photonic-computing",
    emoji: "💡",
    title: "Photonic Computing",
    blurb: "Light-based processors, optical interconnects, and the next computing substrate.",
    pillar: "industrial",
    courses: [
      "Introduction to Photonic Computing",
      "Optical Computing Fundamentals",
      "Silicon Photonics",
      "Photonic Integrated Circuits (PICs)",
      "Optical Interconnects",
      "Laser & Light Sources for Computing",
      "Waveguides & Photonic Components",
      "Electro-Optic Modulators",
      "Photodetectors & Optical Receivers",
      "Optical Neural Networks",
      "Photonic AI Accelerators",
      "Coherent Optical Computing",
      "Quantum Photonics Basics",
      "Photonic Memory Concepts",
      "Optical Switching & Routing",
      "LiDAR & Photonic Sensing",
      "Photonics Manufacturing & Packaging",
      "Photonic Computing for Data Centers",
      "Hybrid Electronic-Photonic Systems",
      "Future of Light-Based Computing",
    ],
  },
  {
    id: "neuromorphic-computing",
    emoji: "🧬",
    title: "Neuromorphic Computing",
    blurb: "Brain-inspired chips, spiking networks, and event-driven intelligence hardware.",
    pillar: "industrial",
    courses: [
      "Introduction to Neuromorphic Computing",
      "Brain-Inspired Computing Fundamentals",
      "Spiking Neural Networks (SNNs)",
      "Neuromorphic Hardware Architectures",
      "Event-Driven Processing",
      "Memristors & Synaptic Devices",
      "Neuromorphic Sensors",
      "Neuromorphic Vision Systems",
      "Analog & Mixed-Signal Neuromorphic Chips",
      "Neuromorphic Learning Algorithms",
      "Energy-Efficient Edge Intelligence",
      "Neuromorphic AI for Robotics",
      "Brain-Computer Interface Basics",
      "Neuromorphic Chip Design",
      "Loihi & Neuromorphic Platforms",
      "Temporal Coding & Spike Timing",
      "Neuromorphic Computing for IoT",
      "Hybrid Neuromorphic-Digital Systems",
      "Neuromorphic Benchmarks & Evaluation",
      "Future of Brain-Inspired Computing",
    ],
  },
  {
    id: "electronics-semi",
    emoji: "⚡",
    title: "Electronics & Semiconductor",
    blurb: "Chips, boards, embedded systems, and semiconductor manufacturing.",
    pillar: "industrial",
    courses: [
      "Embedded Systems",
      "VLSI Design",
      "FPGA",
      "PCB Design",
      "IoT",
      "Robotics Electronics",
      "Semiconductor Manufacturing",
      "Chip Design",
      "Microcontrollers",
    ],
  },
  {
    id: "mechanical-mfg",
    emoji: "🏭",
    title: "Mechanical & Manufacturing",
    blurb: "CAD/CAM, CNC, automation, and production engineering excellence.",
    pillar: "industrial",
    courses: [
      "CAD/CAM",
      "CNC Programming",
      "Industrial Automation",
      "Mechatronics",
      "Robotics",
      "Welding Technology",
      "Additive Manufacturing (3D Printing)",
      "Production Engineering",
      "Quality Control",
    ],
  },
  {
    id: "civil-infra",
    emoji: "🏗️",
    title: "Civil & Infrastructure",
    blurb: "Structures, construction, BIM, and smart infrastructure systems.",
    pillar: "industrial",
    courses: [
      "Structural Engineering",
      "Construction Management",
      "BIM",
      "Smart Cities",
      "Surveying",
      "Transportation Engineering",
      "Environmental Engineering",
    ],
  },
  {
    id: "energy-sustain",
    emoji: "🌱",
    title: "Energy & Sustainability",
    blurb: "Clean power, storage, EVs, grids, and carbon management.",
    pillar: "industrial",
    courses: [
      "Solar Energy",
      "Wind Energy",
      "Battery Technology",
      "EV Systems",
      "Hydrogen Energy",
      "Smart Grids",
      "Carbon Management",
    ],
  },
  {
    id: "automotive",
    emoji: "🚗",
    title: "Automotive",
    blurb: "EV, autonomy, vehicle electronics, and motorsports engineering.",
    pillar: "industrial",
    courses: [
      "Electric Vehicles",
      "Autonomous Driving",
      "Automotive Electronics",
      "Battery Management Systems",
      "Vehicle Design",
      "Motorsports Engineering",
    ],
  },
  {
    id: "finance-fintech",
    emoji: "💰",
    title: "Finance & FinTech",
    blurb: "Markets, modeling, digital finance, and quantitative systems.",
    pillar: "industrial",
    courses: [
      "Investment Banking",
      "Stock Market",
      "Financial Modeling",
      "FinTech",
      "Digital Payments",
      "Blockchain Finance",
      "Risk Management",
      "Quantitative Finance",
    ],
  },
  {
    id: "business-mgmt",
    emoji: "📈",
    title: "Business & Management",
    blurb: "MBA essentials, product, ops, and entrepreneurship skills.",
    pillar: "industrial",
    courses: [
      "MBA Essentials",
      "Marketing",
      "Sales",
      "HR",
      "Operations",
      "Entrepreneurship",
      "Supply Chain",
      "Project Management",
      "Product Management",
    ],
  },
  {
    id: "law-legal",
    emoji: "⚖️",
    title: "Law & Legal",
    blurb: "Corporate, cyber, IP, medical, space, and AI regulatory law.",
    pillar: "industrial",
    courses: [
      "Corporate Law",
      "Cyber Law",
      "Intellectual Property",
      "Medical Law",
      "Space Law",
      "AI Regulation",
      "Contract Management",
    ],
  },
  {
    id: "biotech-life",
    emoji: "🧬",
    title: "Biotechnology & Life Sciences",
    blurb: "Genetics, bioinformatics, discovery, and biomanufacturing.",
    pillar: "industrial",
    courses: [
      "Biotechnology",
      "Genetics",
      "Bioinformatics",
      "Molecular Biology",
      "Drug Discovery",
      "Synthetic Biology",
      "CRISPR",
      "Biomanufacturing",
    ],
  },
  {
    id: "agri-food",
    emoji: "🌾",
    title: "Agriculture & Food",
    blurb: "AgriTech, precision farming, food systems, and agricultural robotics.",
    pillar: "industrial",
    courses: [
      "Precision Agriculture",
      "AgriTech",
      "Food Technology",
      "Dairy Technology",
      "Fisheries",
      "Smart Farming",
      "Agricultural Robotics",
    ],
  },
  {
    id: "media-creative",
    emoji: "🎬",
    title: "Media & Creative",
    blurb: "Design, animation, games, VFX, and immersive content creation.",
    pillar: "industrial",
    courses: [
      "Graphic Design",
      "UI/UX Design",
      "Animation",
      "Video Editing",
      "VFX",
      "Game Development",
      "AR/VR",
      "Digital Content Creation",
    ],
  },
  {
    id: "ind-robotics-auto",
    emoji: "🤖",
    title: "Industrial Robotics & Automation",
    blurb: "PLC, SCADA, IIoT, digital twins, and smart manufacturing lines.",
    pillar: "industrial",
    courses: [
      "Industrial Robotics",
      "PLC Programming",
      "SCADA",
      "Industrial IoT",
      "Smart Manufacturing",
      "Factory Automation",
      "Digital Twins",
    ],
  },
  {
    id: "aviation-logistics",
    emoji: "✈️",
    title: "Aviation & Logistics",
    blurb: "Flight ops, aircraft maintenance, airports, and global logistics.",
    pillar: "industrial",
    courses: [
      "Pilot Ground School",
      "Aircraft Maintenance",
      "Air Traffic Management",
      "Airport Operations",
      "Logistics",
      "Supply Chain",
      "Maritime Logistics",
    ],
  },
  {
    id: "science-research",
    emoji: "🔬",
    title: "Science & Research",
    blurb: "Core sciences, quantum, nano, and scientific computing.",
    pillar: "industrial",
    courses: [
      "Physics",
      "Chemistry",
      "Biology",
      "Mathematics",
      "Quantum Physics",
      "Nanotechnology",
      "Scientific Computing",
    ],
  },
  {
    id: "education-teaching",
    emoji: "📚",
    title: "Education & Teaching",
    blurb: "Pedagogy, edtech, curriculum design, and AI in learning.",
    pillar: "industrial",
    courses: [
      "Teacher Training",
      "Educational Technology",
      "Learning Science",
      "Curriculum Design",
      "AI in Education",
    ],
  },
  {
    id: "hospitality-tourism",
    emoji: "🏨",
    title: "Hospitality & Tourism",
    blurb: "Hotels, culinary arts, tourism, and luxury hospitality ops.",
    pillar: "industrial",
    courses: [
      "Hotel Management",
      "Culinary Arts",
      "Tourism Management",
      "Event Management",
      "Luxury Hospitality",
    ],
  },
  {
    id: "defense-security",
    emoji: "🛡️",
    title: "Defense & Security",
    blurb: "Defense tech, drones, intelligence, and national cybersecurity.",
    pillar: "industrial",
    courses: [
      "Defense Technology",
      "Military AI",
      "Drone Operations",
      "Intelligence Analysis",
      "National Cybersecurity",
      "Unmanned Systems",
    ],
  },
] as const

export const TOTAL_SPACE_COURSES = SPACE_INDUSTRIAL_CATALOG.reduce(
  (sum, cat) => sum + cat.courses.length,
  0,
)

export const SPACE_COURSE_COUNT = SPACE_INDUSTRIAL_CATALOG.filter((c) => c.pillar === "space").reduce(
  (sum, cat) => sum + cat.courses.length,
  0,
)

export const INDUSTRIAL_COURSE_COUNT = SPACE_INDUSTRIAL_CATALOG.filter(
  (c) => c.pillar === "industrial",
).reduce((sum, cat) => sum + cat.courses.length, 0)
